IP2-84 - setup React's module
intive/patronage21-java-frontend pull request #1
Opened 2021-03-22 12:46 UTC by lzolkiewski

2021-03-23 00:03 UTC, kari565 commented on public/manifest.json
> +  "name": "Create React App Sample",
Można by zmienić te nazwy.

2021-03-23 00:03 UTC, kari565 commented on public/index.html
> +    <title>React App</title>
Można by zmienić tytuł strony.

2021-03-23 11:30 UTC, kari565 approved these changes

2021-03-24 14:23 UTC, patronage-java-leaders-2021 requested changes
@lzolkiewski : zerknij prosze na dwa komentarze od @kari565 ktore dobrze byloby uwzglednic w kodzie :). Dziekuję :).

2021-03-24 14:26 UTC, patronage-java-leaders-2021 commented on public/index.html
> +    <title>React App</title>
Proponuje podać nazwę `Patronative` dla spójności z cześcią przygotowną w Javie.

2021-03-24 15:08 UTC, patronage-java-leaders-2021 approved these changes

2021-03-24 20:04 UTC, LukaszCzeronko approved these changes

2021-03-25 08:18 UTC, merged