IP2-361 - add backend errors handling
intive/patronage21-java-frontend pull request #14
Opened 2021-05-12 14:38 UTC by kari565

2021-05-12 18:03 UTC, KrzysztofPawlak commented on src/components/Home/UserListsContainer.js
> +          <NoResults>Brak wyników</NoResults>
do constants albo localisation

2021-05-12 18:04 UTC, KrzysztofPawlak commented on src/components/Home/SearchAlertFrame.js
> +          title="Aplikacja nie mogła połączyć się z usługą"
to też do stałych lub localisation

2021-05-12 18:16 UTC, KrzysztofPawlak commented on src/components/Home/UserListsContainer.js
> +      if (candidates.res.status !== 200 && candidates.res.status !== 422) {
może 400 i 500 jeszcze?

2021-05-16 15:22 UTC, kari565 commented on src/components/Home/UserListsContainer.js
> +      if (candidates.res.status !== 200 && candidates.res.status !== 422) {
W alerts/alertSelectors.js w fukcji checkCommonErrors w default switcha powinno to zostać obsłużone.

2021-05-20 19:36 UTC, KrzysztofPawlak commented on src/alerts/alertSelectors.js
> +      case 200:
czy tu przy 200 nie powinien być break, aby nie sprawdzać reszty?

2021-05-21 00:17 UTC, kari565 commented on src/alerts/alertSelectors.js
> +      case 200:
Nie, bo dla 200 i 422 ma wykonać się to samo.

2021-05-21 15:17 UTC, patronage-java-leaders-2021 requested changes

2021-05-21 15:17 UTC, patronage-java-leaders-2021 commented on src/components/Home/UsersSearchInput.js
> +    if (value.length === 0 || value.length >= 2) setGlobalSearchValue(value);
Warunek można by uprościć i zapisać jako value.length != 1.

2021-05-21 15:20 UTC, patronage-java-leaders-2021 approved these changes
Po uwzględnieniu zmianu dodaj proszę do dev'a. Dzięki :).

2021-05-23 11:50 UTC, KrzysztofPawlak approved these changes

2021-05-24 20:08 UTC, merged