IP2-675 - limit requests during user search
intive/patronage21-java-frontend pull request #23
Opened 2021-05-25 13:30 UTC by kari565

2021-05-26 08:08 UTC, lzolkiewski approved these changes

2021-05-26 10:42 UTC, patronage-java-leaders-2021 requested changes

2021-05-26 10:42 UTC, patronage-java-leaders-2021 commented on src/components/Home/UsersSearchInput.js
> +    () => throttle((value) => setGlobalSearchValue(value), 800),
Proponowałbym wyniesienie do stałej wartości opóźnienia (800). Wówczas jednoznacznie będzie wiadomo jakie jest przeznaczenie wspomnianej wartości.

2021-05-28 12:06 UTC, patronage-java-leaders-2021 approved these changes

2021-05-31 08:09 UTC, merged