IP2-362 - add script that generates custom error pages
intive/patronage21-java-frontend pull request #24
Opened 2021-05-27 09:16 UTC by kari565

2021-06-01 09:08 UTC, lzolkiewski approved these changes

2021-06-01 16:54 UTC, patronage-java-leaders-2021 requested changes

2021-06-01 16:54 UTC, patronage-java-leaders-2021 commented on Dockerfile
>  WORKDIR '/app'
Proponuję modyfikację buildera na poniższą:
`ENV REACT_APP_USER_MODULE_URL=/frontend-api
WORKDIR '/app'
COPY package*.json .
COPY .babelrc .
COPY scripts ./scripts
COPY public ./public
COPY src ./src
RUN npm install \
    && npm run-script generate-error-pages \
    && npm run build
`
Pozwoli to na ominięcie kopiowania nadmiarowych danych oraz optymalizację szybkości budowania obrazu.

2021-06-06 11:56 UTC, KrzysztofPawlak approved these changes

2021-06-10 07:10 UTC, patronage-java-leaders-2021 approved these changes

2021-06-10 18:12 UTC, merged