IP2-677 - limit maximum projects
intive/patronage21-java-frontend pull request #25
Opened 2021-05-27 10:44 UTC by lzolkiewski

2021-05-27 12:35 UTC, kari565 reviewed
Można by było jeszcze zablokować użytkownikowi wpisywanie czegokolwiek/wybór z dropdowna (w przyszłości) do pól projekt i rola jak już jest 5 dodanych projektów. Można by poczekać na dropdowny z tym. 
Fajnie byłoby też dodać może jakąś informacje, żeby użytkownik wiedział dlaczego nie może dodać więcej projektów, np. w postaci Tooltipa.

2021-05-28 13:33 UTC, patronage-java-leaders-2021 requested changes

2021-05-28 13:33 UTC, patronage-java-leaders-2021 commented on src/config/Constants.js
> +export const PROJECTS_LIMIT_MESSAGE = "Limit 5 projektów przekroczony";
Proponuję zmianę komunikatu na coś bardziej "user friendly", np.: "Osiągnięto maksymalny limit projektów w których można równocześnie  uczestniczyć (max 5).", lub "Maksymalny limit projektów w których można uczestniczyć w tym samym czasie wynosi 5.", lub coś podobnego.

2021-05-28 14:30 UTC, patronage-java-leaders-2021 approved these changes

2021-05-31 13:28 UTC, kari565 commented on src/components/User/Edit/NewProject.js
> +  const [anchorElement, setAnchorElement] = React.useState(null);
Tu mogło by być samo useState(null). React jest już zaimportowany.

2021-05-31 13:55 UTC, kari565 approved these changes

2021-05-31 16:18 UTC, merged