Wip ip2 161
intive/patronage21-java-frontend pull request #3
Opened 2021-03-26 13:52 UTC by lzolkiewski

Description.js
SiteHeader.js
User.js
GroupTitle.js

2021-03-27 09:36 UTC, patronage-java-leaders-2021 requested changes
Tutaj są komponenty klasowe a u Karoliny komponenty funkcyjne, trzeba by było ustalić jeden "flow" ponieważ im dalej w las tym będzie coraz ciężej utrzymać kod i dodawać nowe funkcjonalności. Proponuję pisać komponenty funkcyjne ponieważ tak się teraz pisze nowy kod, oczywiście w pracy możecie dostać do utrzymania/dopisania kod który będzie miał x lat i komponenty klasowe też warto znać :)

Ustalcie jedną strukturę folderów i sposób pisania żeby później nie było za dużo konfliktów przy merge'u

2021-03-30 12:20 UTC, kari565 commented on src/components/User/UserHeader.js
> +        </ListItem>
To nie powinno być w liście. Zamień to może na:
   ```
<SiteHeader>
    <Grid container spacing={2} direction="row" alignItems="center">
        <Grid item>
            <Avatar />
        </Grid>
        <Grid item>
            {props.firstName} {props.lastName}
        </Grid>
</Grid>
</SiteHeader>```

2021-03-30 12:20 UTC, kari565 commented on src/views/User/User.js
> +import theme from "../../styles/theme";
Można usunąć ten import i podać theme jako argument funkcji makeStyles:
const useStyles = makeStyles(theme => ({...})); Wtedy również możliwe powinno być wykorzystanie theme, ponieważ w App.js komponenty są w środku .

2021-03-30 13:02 UTC, lzolkiewski commented on src/components/UI/GroupTitle.js
> +import theme from "../../styles/theme";
Poprawiono

2021-03-30 13:02 UTC, lzolkiewski commented on src/components/UI/SiteHeader.js
> +import theme from "../../styles/theme";
Poprawiono

2021-03-30 13:02 UTC, lzolkiewski commented on src/components/User/ContactItem.js
> +import theme from "../../styles/theme";
Poprawiono

2021-03-30 13:02 UTC, lzolkiewski commented on src/components/User/ContactItem.js
> +    },
Usunięto

2021-03-30 13:04 UTC, lzolkiewski commented on src/components/User/ContactItem.js
> +            </div>
Poprawiono
Szerokość guzika zostawiłem na 180px żeby nie zajmował całej szerokość

2021-03-30 13:05 UTC, lzolkiewski commented on src/components/User/ContactItem.js
> +        <ListItem>
Dodałem

2021-03-30 13:05 UTC, lzolkiewski commented on src/components/User/UserHeader.js
> +        </ListItem>
Poprawiłem

2021-03-30 13:05 UTC, lzolkiewski commented on src/views/User/User.js
> +import theme from "../../styles/theme";
Usunąłem

2021-03-30 13:22 UTC, kari565 commented on src/components/User/UserHeader.js
> +    lastName: PropTypes.element.isRequired,
Tutaj są warningi failed prop type. Dopasuj typy propsów  w komponent.propTypes = {..} we wszystkich plikach.
Tutaj powinno być:
```
firstName: PropTypes.string.isRequired,
lastName: PropTypes.string.isRequired,
```

2021-03-30 13:22 UTC, kari565 commented on src/views/User/User.js
> +};
To mogło by iść do folderu mocks

2021-03-30 13:22 UTC, kari565 commented on src/views/User/User.js
> +    return user.projects.map(e => {
element tablicy e nad którym obecnie pracujemy, mógłby mieć bardziej intuicyjną nazwę, np. project albo item.

2021-03-30 13:22 UTC, kari565 commented on src/components/UI/SiteHeader.js
> +            <Typography variant={'h5'} component={'h1'} className={classes.header}>
Ogólnie są różne wielkości tekstów w widoku 1 i 2. Fajnie by było to uspójnić. Wiem, że to ja nazmieniałam, ale teraz to trochę niespójnie jest.

2021-03-31 22:08 UTC, kari565 commented on src/components/User/ContactItem.js
> +    },
Tutaj jak ma szerokość zostać 180px, to możesz zamienić zaznaczone linie na:
```
button: {
    maxWidth: '180px',
    width: '100%'
}
```
Wtedy wielkość Buttonów będzie 180px, a jak okno przeglądarki będzie węższe od 180px to przyciski się dopasują.

2021-03-31 22:24 UTC, kari565 commented on src/components/User/ContactItem.js
> +    },
Może to przesada, ale można by tutaj dodać: wordBreak: 'break-all', żeby dłuższe napisy bez spacji jak email rozbijały się na linie gdy się nie zmieszczą w przeglądarce.

2021-04-01 10:20 UTC, lzolkiewski commented on src/views/User/User.js
> +            <ListItem divider>
Poprawiłem

2021-04-01 10:20 UTC, lzolkiewski commented on src/views/User/User.js
> +//generate list items from array
Usunąłem

2021-04-01 10:21 UTC, lzolkiewski commented on src/views/User/User.js
> +                        </ListGroup>
Stworzyłem komponent ProjectsList

2021-04-01 10:21 UTC, lzolkiewski commented on src/views/User/User.js
> +                {/*user's avatar and first / last name*/}
Pousuwane

2021-04-01 10:21 UTC, lzolkiewski commented on src/components/User/UserHeader.js
> +    lastName: PropTypes.element.isRequired,
Warningi zostały poprawione

2021-04-01 10:22 UTC, lzolkiewski commented on src/views/User/User.js
> +    return user.projects.map(e => {
Zmienione

2021-04-01 10:22 UTC, lzolkiewski commented on src/components/UI/SiteHeader.js
> +            <Typography variant={'h5'} component={'h1'} className={classes.header}>
Poprawione

2021-04-01 10:22 UTC, lzolkiewski commented on src/components/User/ListGroup.js
> +                {props.groupTitle}
Dodałem licznik

2021-04-01 10:23 UTC, lzolkiewski commented on src/components/User/ContactItem.js
> +    },
Poprawiłem wielkość tylko pytanie czy będziemy mieli na tyle małe ekrany żeby z tego korzystały

2021-04-01 10:23 UTC, lzolkiewski commented on src/components/User/ContactItem.js
> +    },
Dodałem

2021-04-01 10:38 UTC, lzolkiewski commented on src/views/User/User.js
> +};
Przeniesione

2021-04-02 09:32 UTC, lzolkiewski commented on src/views/User/User.js
> +        <Container>
Usunąłem Container
Umieściłem go tam ze względu na to, że opis użytkownika ma nico inne niż te w opisie w home 
Co nie zmienia faktu, że były zbyt duże zostały poprawione na 15px

2021-04-02 09:34 UTC, lzolkiewski commented on src/components/User/ProjectsList.js
> +        color: '#9f9f9f',
Został tam zdefiniowany o ile się nie mylę tylko nie exportowany
W trakcie tworzenia nie wiedziałem czy mogę zmieniać czyjś kod :)

2021-04-02 09:36 UTC, lzolkiewski commented on src/components/User/ProjectsList.js
> +        color: '#9f9f9f',
Wyeksportowałem twoja paletę kolorów

2021-04-02 09:42 UTC, lzolkiewski commented on src/components/User/ListGroup.js
> +        background: '#eff9ff',
Wyeksportowałem customPalette

2021-04-02 09:42 UTC, lzolkiewski commented on src/components/User/ProjectsList.js
> +        color: '#9f9f9f',
Dodałem

2021-04-02 09:50 UTC, lzolkiewski commented on src/views/User/User.js
> +            </Container>
Przeniosłem i nieco edytowałem komponent Information

2021-04-02 09:54 UTC, lzolkiewski commented on src/components/UI/SiteHeader.js
> +import {Header} from '../Home/Title';
Zmienione

2021-04-02 10:00 UTC, lzolkiewski commented on src/components/User/ProjectsList.js
> +}
Planowałem zostawić to jako osobna funkcję na wypadek gdyby można jej gdzieś użyć ponownie
Podobna lista do tej mojej jest w Harmonogram spotkań w Grupy technologiczne > Grupa I > Etap I
Można by też dodać kolejną bardziej ogólną i trzymać je w 1 miejscu i używać w zależności od potrzeby

2021-04-02 12:25 UTC, kari565 commented on src/views/User/User.js
> +}));
Tu mam pytanie do liderów @patronage-java-leaders-2021. Czy jeżeli komponent musi zostać dopasowany, w tej chwili wygląda, że tylko paddingi z lewej i prawej, w zależności gdzie jest użyty. To czy takie podejście z przekazywaniem styli jest poprawne? Czy może powinien zostać stworzony oddzielny dedykowany komponent o innych paddingach?

2021-04-02 12:47 UTC, kari565 approved these changes

2021-04-06 08:00 UTC, patronage-java-leaders-2021 commented on src/views/User/User.js
> +}));
W idealnym świecie komponenty powinny być robione według style guide'a i nie powinniśmy im dodawać żadnych wartości poprzez przekazywanie jakichkolwiek wartości. Jak będziemy tworzyć "widoki" dla SPA to zobaczymy jak to będzie współgrało ze sobą

2021-04-06 08:17 UTC, patronage-java-leaders-2021 commented on src/views/User/User.js
> +    return (
Ten widok będzie musiała być jeszcze podzielony na komponenty ale jako makieta zostawmy to co jest.

2021-04-06 08:17 UTC, patronage-java-leaders-2021 approved these changes

2021-04-06 08:26 UTC, merged