IP2 - 790 - display login
intive/patronage21-java-frontend pull request #31
Opened 2021-06-04 11:53 UTC by lzolkiewski

2021-06-06 09:35 UTC, kari565 reviewed
Login może się zbyt mocno zbliżyć do imienia i nazwiska przy małych rozdzielczościach ekranu. Fajnie było by dodać jakiś odstęp między tymi elementami. 
 
![image](https://user-images.githubusercontent.com/10207332/120919678-2234c600-c6bb-11eb-885a-c4aa4d266612.png)

2021-06-06 09:35 UTC, kari565 commented on src/components/UI/SearchInput.js
> +        title={TOOLTIP_MESSAGE}
Ja bym przekazała w propsach tytuł, ponieważ SearchInput jest bardziej ogólnym komponentem. Mógłby być wykorzystany jako wyszukiwarka w innych widokach i jest w folderze UI. Natomiast komponent UserSearchInput jest przeznaczony do wyszukiwaia użytkowników i komunikat z Tooltipa jest przeznaczony specjalnie dla niego.

2021-06-08 15:34 UTC, patronage-java-leaders-2021 approved these changes

2021-06-08 15:41 UTC, patronage-java-leaders-2021 requested changes

2021-06-08 15:41 UTC, patronage-java-leaders-2021 commented on src/components/Home/UserList.js
> +      <ListItemText className={classes.tableRight} primary={user.login} />
Proponuję ująć login w nawiasy "()", co powinno poprawić czytelność w przypadku małych szerokości ekranu. Całość powinna zachować aktualnie zaproponowany format.

2021-06-08 15:54 UTC, patronage-java-leaders-2021 approved these changes

2021-06-09 07:51 UTC, kari565 approved these changes

2021-06-09 08:07 UTC, merged