IP2-664 dropdown projects and roles
intive/patronage21-java-frontend pull request #32
Opened 2021-06-05 09:21 UTC by KrzysztofPawlak

2021-06-06 14:33 UTC, kari565 reviewed
Po odświeżeniu strony gdy wybiera się z dropdowna projekt, do którego nie jest jeszcze przypisany użytkownik, przeładowuje się cała strona. Gdyby dostępne role dla projektów ściągały się w komponencie do wyboru roli i ich stan był trzymany w atomie tylko dla nich przeznaczonym, to przeładowywałby się tylko komponent do wyboru roli. Teraz  wydaje mi się, że elementy pośredniczące w przekazywaniu ściągniętych ról dla pola do wyboru roli również się przeładowują przy pierwszym ściągnięciu ról dla danego projektu. Potem są one zapamiętywane i już się nie przeładowują.

2021-06-06 14:33 UTC, kari565 commented on src/components/User/Edit/EditProjectRolesSelectInput.js
> +          {props.propertyName === "name" ? PROJECT_LABEL : PROJECT_ROLE_LABEL}
Labele są trochę nieczytelne, kiedy pojawiają się na górze dropdowna. Był do tego wcześniej zgłoszony bug przez QA. To samo dla nowego projektu i dla nowej roli:
![image](https://user-images.githubusercontent.com/10207332/120928192-e7935380-c6e3-11eb-9017-70c4ce5c0b81.png)

2021-06-06 17:10 UTC, kari565 commented on src/components/User/Edit/NewProject.js
> +        {item(newProjectName, PROJECT_LABEL, setNewProjectName, props.projectsNames)}
Wydaje mi się, że lepiej by było dać pierwszy projekt z listy jako wartość początkowa dropdowna. W tej chwili gdy nie ma realnego projektu w dropdownie z rolami wyświetla się:
![image](https://user-images.githubusercontent.com/10207332/120933500-c1c57900-c6fa-11eb-82b2-36b5249c3032.png)

2021-06-07 09:24 UTC, lzolkiewski commented on src/components/User/Edit/NewProject.js
> +    }
Mógłbyś tutaj jeszcze sprawdzać czy dany projekt nie jest przypadkiem już przypisany do użytkownika
i wyświetlać jakiś komunikat czemu nie można dodać projektu.

2021-06-08 16:08 UTC, patronage-java-leaders-2021 commented on src/components/User/Edit/NewProject.js
> +        {item(newProjectName, PROJECT_LABEL, setNewProjectName, props.projectsNames)}
W przypadku dropdowna z projektami, domyślne powinna prezentować się wartość "wybierz projekt" - czyli wartość początkowa. Dropdown z rolami jest wówczas nieaktywny. W przypadku gdy z backendu nie otrzymamy z projektami lub rolami, dropdown powinien mieć wartość "brak projeków" lub "brak ról" i być nieaktywy.
W razie pytań lub wątpliwości zapraszam do kontaktu :).

2021-06-08 16:10 UTC, patronage-java-leaders-2021 requested changes

2021-06-08 16:10 UTC, patronage-java-leaders-2021 commented on src/components/User/Edit/NewProject.js
> +        {item(newProjectName, PROJECT_LABEL, setNewProjectName, props.projectsNames)}
W przypadku dropdowna z projektami, domyślne powinna prezentować się wartość "wybierz projekt" - czyli wartość początkowa. Dropdown z rolami jest wówczas nieaktywny. W przypadku gdy z backendu nie otrzymamy z projektami lub rolami, dropdown powinien mieć wartość "brak projeków" lub "brak ról" i być nieaktywy.
W razie pytań lub wątpliwości zapraszam do kontaktu :).

2021-06-12 22:20 UTC, lzolkiewski commented on src/components/User/Edit/NewProject.js
> +          props.projectsNames.length === 0 ? "brak projektów" : newProjectName,
Możesz poprzenosić te stringi do stałych

2021-06-12 22:45 UTC, KrzysztofPawlak commented on src/components/User/Edit/NewProject.js
> +          props.projectsNames.length === 0 ? "brak projektów" : newProjectName,
po to były te komentarze TODO

2021-06-20 17:00 UTC, kari565 reviewed
Komunikat błędu pokazuje się zaraz po zmianie/wyborze projektu. Dotyczy on niewybrania roli w projekcie. Użytkownik w tamtym momencie nie mógł jeszcze wybrać roli, ponieważ dopiero co wybrał projekt. Wydaje mi się, że komunikat błędu mógłby pojawiać się przy kliknięciu "Zatwierdź" i ewentualnie plusa.

Gdy za pierwszym razem po przeładowaniu strony przechodzi się z widoku listy użytkowników do profilu użytkownika to najpierw pojawiają się wszystkie elementy oprócz projektów z rolami. Kontakty pojawiają się z lewej strony, następnie gdy załadują się projekty, kontakty przesuwają się i projekty pojawiają się w ich miejscu z lewej strony. Powinno się to poprawić.

2021-06-21 11:51 UTC, lzolkiewski approved these changes

2021-06-22 11:13 UTC, kari565 approved these changes

2021-06-22 13:40 UTC, patronage-java-leaders-2021 approved these changes

2021-06-22 14:57 UTC, merged